name: InstaBioBot Automation

on:
  schedule:
    - cron: "0 8,20 * * *"  # Runs at 8 AM & 8 PM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-bio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches

      - name: Set up Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -d $HOME/gradle gradle-8.9-bin.zip
          echo "$HOME/gradle/gradle-8.9/bin" >> $GITHUB_PATH
      
      - name: Verify Gradle Version
        run: gradle -version

      - name: Install Docker & Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg \
              lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Check Docker version
        run: docker --version
        
      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Build and run InstaBioBot container
        run: |
          echo "USER=${{ secrets.IG_USER }}" > .env
          echo "PASS=${{ secrets.IG_PASS }}" >> .env
          
          docker-compose build
          docker-compose up --abort-on-container-exit || docker-compose logs
