name: InstaBioBot Automation

on:
  schedule:
    - cron: "0 8,20 * * *"  # Runs at 8 AM & 8 PM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-bio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker & Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Build and run InstaBioBot container
        run: |
          echo "USER=${{ secrets.IG_USER }}" > .env
          echo "PASS=${{ secrets.IG_PASS }}" >> .env
          
          docker-compose build
          docker-compose up --abort-on-container-exit